---
title: "Project"
output: html_notebook
---

Import libraries
```{r}
library(gRbase)
library(gRim)
library("Rgraphviz")
library("igraph")
```

Read the dataset
```{r}
setwd("C:/Users/simon/Desktop/Graphical Model/probabilistic_modelling")
data <- read.csv(file = 'heart.csv')
data <- data[c(14,1,2,3,4,5,6,7,8,9,10,11,12,13)]
data$target <- factor(data$target)
data$sex <- factor(data$sex)
data$cp[data$cp>= 1] <- 1
data$cp[data$cp < 1]  <- 0
data$cp <- factor(data$cp)
data$fbs <- factor(data$fbs)
data$restecg <- factor(data$restecg)
data$exang <- factor(data$exang)
data$slope <- factor(data$slope)
data$ca <- factor(data$ca)
data$thal <- factor(data$thal)
data$chol[data$chol > 240]  <- 1
data$chol[data$chol <= 240]  <- 0
names(data)[names(data) == "chol"] <- "hyperchol"
data$hyperchol <- factor(data$hyperchol)
head(data)
```


age, trestbps, thalach, oldpeak are continuous varibale, while the remaining variables
are discrete. Therefore mixed interaction models are applied

```{r}
data_table <- as.table(ftable(data[c(1,3,4,6,7,8,10,12,13)]))
data_table
```

```{r}
m.init <- dmod(~.^.,data=data_table) # saturated model
x11()
plot(m.init)

# default  values:
# penalty parameter = 2 (AIC)
# direction: backward
m1 <- stepwise(m.init)
x11()
plot(m1)

# parameter of penalization is log(N)
m2 <- stepwise(m.init,k=log(sum(data_table)))
x11()
plot(m2)



x11()
par(mfrow=c(1,3))
myplot(as(m.init,"igraph"),main="Initial model")
myplot(as(m1,"igraph"), main="AIC")
myplot(as(m2,"igraph"), main="BIC")



# direction: forward
data("mildew")

mildew.init <- dmod(~.^1,data=mildew)
x11()
plot(mildew.init)

m.mildew  <- stepwise(mildew.init,k=log(sum(mildew)),direction="forward",details=1)
x11()
plot(m.mildew)

```

```{r}


```

```{r}

```

```{r}


```


